package com.jk.bean.gkk;
// Generated 2018-4-9 14:44:24 by Hibernate Tools 4.3.1.Final


/**
 * TShopdalei generated by hbm2java
 */

public class TShopdalei {

	private Integer id;
	private String name;
	private String notes;


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getnotes() {
		return this.notes;
	}

	public void setnotes(String notes) {
		this.notes = notes;
	}

	/* (non-Javadoc)    
	 * @see java.lang.Object#toString()    
	 */
	@Override
	public String toString() {
		return "TShopdalei [id=" + id + ", name=" + name + ", notes=" + notes + "]";
	}

}
